apiVersion: v2
name: ejabberd
description: ejabberd XMPP server helm chart
type: application
version: 0.1.0
appVersion: "24.12-k8s"
keywords:
  - xmpp
  - mqtt
  - sip
  - stun

maintainers:
  - name: dhanzhelo
    email: d.hanzhelo@indevlab.com
